name = input("enter the name\t")
age = int(input(f"{name}\tenter your age\t"))
course = input(f"{name}\t which course you want to join\t")
contact = int(input(f"{name}\t enter your contact no\t"))
confirmation=input(f"{name} the above information is correct if then type yes or else no\t")